import { createClient } from '@supabase/supabase-js';
import './style.css';
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
const app=document.querySelector('#app');let positions=[],candidates=[],settings=null,code='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(){const [p,c,s]=await Promise.all([supabase.from('positions').select('*').order('id'),supabase.from('candidates').select('*').order('position_id').order('id'),supabase.from('election_settings').select('*').limit(1).maybeSingle()]);if(p.error)throw p.error;if(c.error)throw c.error;positions=p.data||[];candidates=c.data||[];settings=s.data||{};}
function home(msg=''){app.innerHTML=`<main class="wrap"><header><b>GOOD CITIZEN SCHOOL</b><h1>Student Prefect Election 2026</h1><p>One ballot per student.</p></header><section class="card"><h2>Student Voting</h2><form id="f"><input id="code" placeholder="Enter your voting code" required><button>Continue to Vote</button></form><button class="alt" id="results">View Results</button><div class="status">${settings.is_open?'Voting is open.':'Voting has not started.'}</div>${msg?`<div class="err">${esc(msg)}</div>`:''}</section></main>`;document.querySelector('#f').onsubmit=e=>{e.preventDefault();code=document.querySelector('#code').value.trim();if(!settings.is_open)return home('Voting has not started.');vote();};document.querySelector('#results').onclick=results;}
function vote(){const active=candidates.filter(c=>c.is_active!==false);app.innerHTML=`<main class="wrap"><header><b>GOOD CITIZEN SCHOOL</b><h1>Your Ballot</h1></header><form id="ballot">${positions.map(p=>`<section class="card"><h2>${esc(p.name)}</h2><div class="grid">${active.filter(c=>String(c.position_id)===String(p.id)).map(c=>`<label class="candidate"><input type="radio" name="p-${p.id}" value="${esc(c.id)}" required><span>${esc(c.name)}</span></label>`).join('')}</div></section>`).join('')}<button>Submit Ballot</button></form></main>`;document.querySelector('#ballot').onsubmit=async e=>{e.preventDefault();const selections={};for(const p of positions)selections[p.id]=document.querySelector(`input[name="p-${p.id}"]:checked`).value;const {error}=await supabase.rpc('cast_ballot',{p_voting_code:code,p_selections:selections});if(error)return voteError(error.message);app.innerHTML='<main class="wrap"><section class="card center"><h1>Vote submitted ✓</h1><p>Your ballot has been recorded.</p><button id="r">View Results</button></section></main>';document.querySelector('#r').onclick=results;};}
function voteError(m){app.innerHTML=`<main class="wrap"><section class="card"><h1>Vote not submitted</h1><div class="err">${esc(m)}</div><button id="back">Back</button></section></main>`;document.querySelector('#back').onclick=home;}
async function results(){app.innerHTML='<main class="wrap"><section class="card"><h1>Results</h1><p>Loading…</p></section></main>';const [{data:v,error:ve},{data:c,error:ce}]=await Promise.all([supabase.from('votes').select('candidate_id'),supabase.from('candidates').select('id,name,position_id').eq('is_active',true)]);if(ve||ce){app.innerHTML=`<main class="wrap"><section class="card err">${esc((ve||ce).message)}</section></main>`;return;}const count={};(v||[]).forEach(x=>count[x.candidate_id]=(count[x.candidate_id]||0)+1);app.innerHTML='<main class="wrap"><header><b>GOOD CITIZEN SCHOOL</b><h1>Election Results</h1><p>Percentages only.</p></header>'+positions.map(p=>{const cs=(c||[]).filter(x=>String(x.position_id)===String(p.id));const total=cs.reduce((n,x)=>n+(count[x.id]||0),0)||1;return `<section class="card"><h2>${esc(p.name)}</h2>${cs.map(x=>`<div class="row"><span>${esc(x.name)}</span><b>${((count[x.id]||0)/total*100).toFixed(1)}%</b></div>`).join('')}</section>`}).join('')+'</main>';}
load().then(home).catch(e=>app.innerHTML=`<main class="wrap"><section class="card"><h1>Connection error</h1><p>${esc(e.message)}</p></section></main>`);
